### ISSUE TITLE
[Easy] Remove Duplicates From Sorted Array

### ISSUE THREAD

**Issue by gulatikeshav** [Vishwas2/Hacktoberfest2023#25] opened 2023-10-10 07:18 UTC
Given an integer array nums sorted in non-decreasing order, remove the duplicates [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) such that each unique element appears only once. The relative order of the elements should be kept the same. Then return the number of unique elements in nums.

Consider the number of unique elements of nums to be k, to get accepted, you need to do the following things:

Change the array nums such that the first k elements of nums contain the unique elements in the order they were present in nums initially. The remaining elements of nums are not important as well as the size of nums.
Return k.
Custom Judge:

The judge will test your solution with the following code:

```
int[] nums = [...]; // Input array
int[] expectedNums = [...]; // The expected answer with correct length

int k = removeDuplicates(nums); // Calls your implementation

assert k == expectedNums.length;
for (int i = 0; i < k; i++) {
    assert nums[i] == expectedNums[i];
}
```
If all assertions pass, then your solution will be accepted.

 

Example 1:

Input: nums = [1,1,2]
Output: 2, nums = [1,2,_]
Explanation: Your function should return k = 2, with the first two elements of nums being 1 and 2 respectively.
It does not matter what you leave beyond the returned k (hence they are underscores).

**Comment by gulatikeshav** [comment] 2023-10-10 07:18
please assign me this issue

**Comment by Vishwas2** [comment] 2023-10-10 10:03
@gulatikeshav please don't create a pull request before the issue is assigned to you.

**Comment by Jatingupta9120** [comment] 2023-10-10 10:18
hey plz assign this issue to me

**Comment by Vishwas2** [comment] 2023-10-10 12:25
@Jatingupta9120 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.

**Closed** 2023-10-10 15:53 UTC
Labels: good first issue, hacktoberfest-accepeted

**Comment by Jatingupta9120** [comment] 2023-10-11 06:24
> @Jatingupta9120 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.
ye to closed h ab kr skta hun?

**Comment by Vishwas2** [comment] 2023-10-11 12:17
> > @Jatingupta9120 I have assigned this to you 😊 . Please read CONTRIBUTING.md to understand how to contribute to this repo and please give this repo a ⭐to show your support.
> > ye to closed h ab kr skta hun?

No now you cannot work on this issue since It has already been solved.
